//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.UsersApp.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restaurant.UsersApp.Core.Resources.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Deleted Successfully.
        /// </summary>
        public static string DeleteUserSuccessfully {
            get {
                return ResourceManager.GetString("DeleteUserSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Deleted UnSuccessfully.
        /// </summary>
        public static string DeleteUserUnSuccessfully {
            get {
                return ResourceManager.GetString("DeleteUserUnSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not Successfully.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Correct.
        /// </summary>
        public static string PasswordIsCorrect {
            get {
                return ResourceManager.GetString("PasswordIsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not Correct.
        /// </summary>
        public static string PasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("PasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Role Added Successfully.
        /// </summary>
        public static string RoleAdded {
            get {
                return ResourceManager.GetString("RoleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Role is Exist in System.Please Insert new Role in System.
        /// </summary>
        public static string RoleIsExist {
            get {
                return ResourceManager.GetString("RoleIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not Exist Any role in System.Please Insert Role in Data Base.
        /// </summary>
        public static string RoleIsNotExist {
            get {
                return ResourceManager.GetString("RoleIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In Successfully.
        /// </summary>
        public static string SignInSuccessfully {
            get {
                return ResourceManager.GetString("SignInSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New User Added Successfully.
        /// </summary>
        public static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User is exist.Please Log in.
        /// </summary>
        public static string UserIsExist {
            get {
                return ResourceManager.GetString("UserIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not Found.Please First Insert a new user..
        /// </summary>
        public static string UserIsNotExist {
            get {
                return ResourceManager.GetString("UserIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New User Roles Added Successfully.
        /// </summary>
        public static string UserRoleAdded {
            get {
                return ResourceManager.GetString("UserRoleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is exist for the user.
        /// </summary>
        public static string UserRoleIsExist {
            get {
                return ResourceManager.GetString("UserRoleIsExist", resourceCulture);
            }
        }
    }
}
